GET https://phonebook-backend-vcdv.onrender.com/api/persons
Content-Type: application/json

###
GET https://phonebook-backend-vcdv.onrender.com/api/persons/1
Content-Type: application/json

###
DELETE https://phonebook-backend-vcdv.onrender.com/api/persons/4


###
POST https://phonebook-backend-vcdv.onrender.com/api/persons
Content-Type: application/json

{
    "name":"Timo",
    "number":"076 281 39 27"
}
###
GET http://localhost:3001/api/persons
Content-Type: application/json

###
GET http://localhost:3001/api/persons/695cb44cf0425cafd9b2ecd6
Content-Type: application/json

###
DELETE http://localhost:3001/api/persons/695cb0ded2f6f0e1289a37af


###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"Timo",
    "number":"076 281 39 27"
}

